# Generated by Django 2.1.7 on 2019-03-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-creation_date',), 'verbose_name': 'tweet', 'verbose_name_plural': 'tweets'},
        ),
    ]
